# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config

2.3.5


<function numpy.show_config(mode='stdout')>

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
# Z = np.zeros((10,10))
# print("%d byte" % (Z.size*Z.itemsize))

print("%d bytes" % Z.nbytes)

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [4]:
help(np.add)
np.info(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:

Z = np.zeros(10)
Z[4] = 1
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:

Z = np.arange(10,50)
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
Z = np.arange(50)
Z= Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [22]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.42600761 0.24738816 0.68392936]
  [0.60643189 0.39754306 0.63777129]
  [0.7464592  0.18908905 0.5437705 ]]

 [[0.79652765 0.63836236 0.48484896]
  [0.19714042 0.34077729 0.37620115]
  [0.1296263  0.87604442 0.79192297]]

 [[0.387252   0.77274398 0.2477355 ]
  [0.21185475 0.40877203 0.96586538]
  [0.26544939 0.26499422 0.84706562]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
z = np.random.random((10,10))
Zmin, Zmax = Z.min, Z.max()
print(Zmin, Zmax)

<built-in method min of numpy.ndarray object at 0x00000248A1A242D0> 0.965865379707409


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
Z = np.random.random(30)
m = Z.mean()
print(Z)
print(m)

[0.65394759 0.23066267 0.30254519 0.47459616 0.63998454 0.95569536
 0.04197783 0.79481785 0.04175111 0.64190962 0.08194657 0.55519986
 0.23661655 0.31054509 0.03681725 0.31326544 0.17295386 0.69463349
 0.03839904 0.17600037 0.27513323 0.52266734 0.57337189 0.81407432
 0.81754093 0.46776415 0.50703017 0.78166271 0.22223657 0.5057694 ]
0.42938387150925694


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
z = np.ones((5,5))
z = np.pad(Z, pad_width=1, mode='constant', constant_values = 0)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [42]:
print(0*np.nan)
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3* 0.1

nan


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [43]:
Z = np.diag (1+np.arange(4), k= -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [48]:
Z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [49]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [56]:
Z = np.tile( np.array([[0,1],[1,0]]),(3,3))
print(Z)


[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [58]:
z = np.random.random((5,5))
Z = (z - np.mean(z)) / (np.std(z))
print(z)
print(Z)

[[0.94239409 0.85498216 0.01324885 0.64942262 0.57258903]
 [0.74396405 0.10785173 0.6436962  0.50059968 0.24889837]
 [0.30591882 0.27306376 0.18887112 0.64729209 0.69639014]
 [0.66158727 0.11205587 0.54147978 0.44296296 0.25802286]
 [0.04240885 0.92523738 0.59390798 0.64880563 0.05915341]]
[[ 1.69877237  1.38641988 -1.62137899  0.65188588  0.37733335]
 [ 0.98971449 -1.28333077  0.63142342  0.12009098 -0.77932325]
 [-0.57556981 -0.69297212 -0.993821    0.64427275  0.81971676]
 [ 0.6953543  -1.26830793  0.26616944 -0.08586457 -0.74671834]
 [-1.51718039  1.63746561  0.45351319  0.64968114 -1.45734638]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [60]:
colour = np.dtype([("r", np.ubyte),
                   ("g", np.ubyte),
                   ("b", np.ubyte),
                   ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [62]:
Z = np.matmul(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [64]:
Z = np.arange(11)
Z[(3 < Z) & (Z<8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [65]:
print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Is illegal:
Z <Z> Z
Z <- Z

Is legal:
Z**Z
2<< Z >> 2
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [68]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Dani_\AppData\Local\Temp\ipykernel_3140\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Dani_\AppData\Local\Temp\ipykernel_3140\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Dani_\AppData\Local\Temp\ipykernel_3140\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [73]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-9. 10.  2. -5. -9. -1. -3. -5. -1. -1.]
[-9. 10.  2. -5. -9. -1. -3. -5. -1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [75]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 4 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [79]:
default = np.seterr(all="ignore")
Z = np.ones(1) / 0 

_ = np.seterr(**default)

with np.errstate(all = "ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [80]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [83]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2025-11-26
2025-11-27
2025-11-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [85]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [87]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out= A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [91]:
z = np.random.uniform(0,10,10)
print(z - z %1)
print(z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(z))


[6. 9. 0. 3. 8. 2. 8. 9. 0. 3.]
[6. 9. 0. 3. 8. 2. 8. 9. 0. 3.]
[inf]
[-9223372036854775808]
[6. 9. 0. 3. 8. 2. 8. 9. 0. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [95]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

Z = np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [96]:
def generate():
    for x in range (10):
        yield x
z= np.fromiter(generate(),dtype=float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [97]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [99]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03029222 0.06855355 0.13921173 0.41800246 0.42212335 0.45434484
 0.56747454 0.6560329  0.70172152 0.924199  ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [100]:
Z = np.arange(10)
np.add.reduce(z)

np.float64(5.583884648131447)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [102]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print (equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [106]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [107]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.73626206 0.76583458 0.71563681 1.24326794 0.7681797  0.9178771
 0.92753777 0.92419423 0.53789906 0.75405251]
[0.1716601  0.36536165 0.50950887 0.82880688 0.57425537 0.26288504
 0.76472154 1.0454247  0.87125749 0.74806848]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [108]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.78904    0.21635928 0.50137166 0.73167028 0.49292714 0.53065763
 0.49296447 0.         0.6422027  0.75288927]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [110]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [111]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [112]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [5]:
np.set_printoptions(threshold=float("inf"))
Z =  np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [117]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

44


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [120]:
Z = np.zeros(10,[('position',[('x', float, 1),
                             ('y', float, 1)]),
                ('color', [('r', float, 1),
                           ('g',float,1),
                           ('b', float,1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [36]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# import scipy
# import scipy.spatial
# Z = np.random.random((10,2))
# D = scipy.spatial.distance,cdist(Z,Z)
# print(D)

[[0.         0.75095382 0.24801582 0.87062219 0.802423   0.71176802
  0.423774   0.16154447 0.70656839 0.39956895]
 [0.75095382 0.         0.62312617 0.52513052 0.16208073 0.35674578
  0.60790435 0.70859219 0.045893   0.56754808]
 [0.24801582 0.62312617 0.         0.89403854 0.62966552 0.49160597
  0.54187311 0.35596646 0.58478009 0.15214767]
 [0.87062219 0.52513052 0.89403854 0.         0.68634128 0.85994437
  0.48216967 0.73840643 0.51108533 0.92492255]
 [0.802423   0.16208073 0.62966552 0.68634128 0.         0.23755329
  0.73492903 0.79086947 0.1874393  0.53763581]
 [0.71176802 0.35674578 0.49160597 0.85994437 0.23755329 0.
  0.7766066  0.74834785 0.3549943  0.36273007]
 [0.423774   0.60790435 0.54187311 0.48216967 0.73492903 0.7766066
  0.         0.27068173 0.56501598 0.64015495]
 [0.16154447 0.70859219 0.35596646 0.73840643 0.79086947 0.74834785
  0.27068173 0.         0.66272928 0.49384638]
 [0.70656839 0.045893   0.58478009 0.51108533 0.1874393  0.3549943
  0.56501598 0.6627292

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [124]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[84 19 15 73 10  6 65 69 60 98]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype = int, filling_values = 0)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [126]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [127]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [129]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [130]:
X = np.random.rand(5,10)
Y = X-X.mean(axis=1).reshape(-1,1)
print(Y)

[[-0.31192251  0.1681433   0.49947583  0.03021736 -0.20762093 -0.15974999
  -0.15840799  0.04128339  0.11165845 -0.01307691]
 [-0.30286126  0.36074734  0.00365758  0.10297845 -0.1753629  -0.12460386
  -0.26475827  0.07735937 -0.23814898  0.56099252]
 [ 0.21771118  0.13411993 -0.29354344 -0.0135816   0.24693126 -0.39852472
   0.24286252 -0.03724599 -0.25230472  0.1535756 ]
 [-0.16585286 -0.10144642 -0.25150991  0.61468387 -0.24565044  0.41840504
  -0.19937036  0.05116503 -0.04238067 -0.07804327]
 [-0.40045541 -0.30955176  0.49896371  0.18864271  0.02015334 -0.104585
   0.22008289 -0.28903643  0.05844295  0.117343  ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [132]:
Z = np.random.randint(0,11,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 9 8]
 [8 9 3]
 [6 0 3]]
[[6 0 3]
 [3 9 8]
 [8 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [137]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

z = np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [138]:
Z =  np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)


0.4790176035915099


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [140]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z [...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [141]:
class NamedArray(np.ndarray):
    def __new__(cls,array, name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None : return
        self.name = getattr(obj, 'name', "no name")
    
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [142]:
z = np.ones(10)
I = np.random.randint(0,len(z),20)
z += np.bincount(I, minlength=len(Z))
print(z)

[1. 2. 6. 2. 4. 3. 4. 4. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [143]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [145]:
w, h = 256, 256
I = np.random.randint(0,4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis = 0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [146]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2]+ (-1,)).sum(axis=-1)
print(sum)

[[37 62 48 53]
 [44 34 64 63]
 [64 42 63 71]]
[[37 62 48 53]
 [44 34 64 63]
 [64 42 63 71]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [149]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.29332057 0.42372464 0.57264799 0.54458736 0.4671214  0.60797117
 0.53128553 0.48914289 0.5593101  0.50052436]
0    0.293321
1    0.423725
2    0.572648
3    0.544587
4    0.467121
5    0.607971
6    0.531286
7    0.489143
8    0.559310
9    0.500524
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [3]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i",A,B)

array([1.11778473, 0.27943106, 1.30808213, 0.63068272, 1.77342493])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [5]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)- 1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [7]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B [:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [10]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [11]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis= 1)
G = F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 3, 22) ( 3, 46) ( 4, 48) ( 4, 58) ( 4, 78) ( 4, 88) ( 5, 38) ( 5, 95)
 (11, 12) (11, 62) (12, 62) (18, 86) (18, 99) (20, 44) (20, 46) (22, 46)
 (25, 64) (25, 90) (32, 80) (32, 99) (38, 95) (44, 46) (45, 97) (45, 98)
 (48, 88) (58, 78) (64, 90) (80, 99) (86, 99) (97, 98)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = C
print(A)
A = np.repeat(np.arange(len(C)),C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [15]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n -1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [17]:
from numpy.lib import stride_tricks

def rolling(a,window):
    shape = (a.size - window + 1 , window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides = strides )
Z = rolling(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [19]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out = Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)



array([ 0.88859171,  0.15308903, -0.99817236,  0.83579411,  0.40708962,
       -0.13399927, -0.13720937,  0.38453563, -0.71042991, -0.30421484,
       -0.81391235,  0.81914575, -0.54100696,  0.13922767,  0.8723504 ,
       -0.71423183, -0.71768872,  0.43604176, -0.37582637, -0.30745231,
       -0.34683341, -0.35711321, -0.73581231,  0.22027913,  0.48117093,
        0.63625642, -0.21547265, -0.65083193, -0.3719287 , -0.95372608,
       -0.0954043 , -0.5443944 , -0.95932726,  0.88869291,  0.10171323,
       -0.51670399, -0.66206611, -0.94728149, -0.47398435,  0.73620107,
        0.28341668,  0.1669727 ,  0.70721968,  0.21663831,  0.53349533,
       -0.87703079, -0.77042224, -0.65840851, -0.92975242, -0.76947399,
        0.04604176, -0.48219164, -0.50709682, -0.36730811, -0.74088823,
        0.18880471, -0.55769795, -0.34210712, -0.27926297, -0.10138128,
       -0.88464503, -0.26411518,  0.91438463, -0.62497577, -0.20185204,
       -0.96297121, -0.2742949 ,  0.91807827, -0.26302107,  0.86

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [22]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))

def distance_faster(P0,P1,p):
    v = P1- P0 
    v[:,[0,1]] = v[:,[1,0]]
    v[:,1]*=-1 
    norm = np.linalg.norm(v,axis=1)   
    r = P0 - p
    d = np.abs(np.einsum("ij,ij->i",r,v)) / norm 

    return d

print(distance_faster(P0, P1, p))


[ 4.14814708 15.65363905 10.73774787  7.13301824 13.05864646 11.64826265
  7.1908769   8.13301946  5.48315072  6.14770589]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [6]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
P = np.random.uniform(-10, 10, (10, 2))

v = P1[:, None, :] - P0[:, None, :]

r = P0[:, None, :] - P[None, :, :]

cross_prod_mag = v[..., 0] * r[..., 1] - v[..., 1] * r[..., 0]

norm_v = np.sqrt(np.sum(v**2, axis=-1))

D = np.abs(cross_prod_mag) / norm_v
print(D)

[[ 6.17476681  3.34451086  3.28419442  7.17643658  0.60690742  9.8355066
  15.67098727 12.83544513  1.15226296  3.14274852]
 [ 7.97070729  6.02533835  1.25676905  9.60683354  1.16959144  6.84045449
  13.43606247 10.09025589  2.2311104   5.67183825]
 [11.94713348  7.08000711  3.50358982 10.95014487  6.42555502  4.6612497
   7.27902178  6.41139071  9.87446743  7.34953514]
 [ 9.77703851  4.26124703  3.26415239  7.58479416  5.91843091  4.77733609
   4.84640868  5.42909114  9.99251682  4.80752866]
 [11.32933547  7.31396253  2.07874134 11.30107184  4.98062339  5.56298716
   9.88891562  8.0023991   7.70222638  7.35627347]
 [ 1.07892084  4.31176436  6.08717971  0.7851613   3.3208825  14.26380114
  15.090732   15.24978067  0.61741601  3.84099274]
 [ 4.22847769  0.46257691  4.45850222  3.45837205  1.52421645 12.54557556
  15.58908731 14.47158118  1.77019968  0.24605553]
 [15.61641058 11.00290559  6.83827317 14.94065006  9.77453163  1.20818077
   4.42397681  3.20464561 13.00177092 11.19734638]
 [

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [8]:
def extract_centered_subpart(Z, center, shape, fill_value=0):

    h, w = Z.shape
    sh, sw = shape
    r, c = center

    start_r = r - sh // 2
    end_r = start_r + sh
    start_c = c - sw // 2
    end_c = start_c + sw

    # Calculate padding needed: (pad_before, pad_after)
    pad_r_before = max(0, -start_r)
    pad_r_after = max(0, end_r - h)
    pad_c_before = max(0, -start_c)
    pad_c_after = max(0, end_c - w)

    # Pad the array Z
    Z_padded = np.pad(Z,
                      ((pad_r_before, pad_r_after), (pad_c_before, pad_c_after)),
                      mode='constant',
                      constant_values=fill_value)

    # Recalculate slice coordinates on the padded array
    p_start_r = start_r + pad_r_before
    p_end_r = end_r + pad_r_before
    p_start_c = start_c + pad_c_before
    p_end_c = end_c + pad_c_before

    # Extract the subpart
    return Z_padded[p_start_r:p_end_r, p_start_c:p_end_c]

Z = np.arange(25).reshape(5, 5)
center = (2, 2)
shape = (3, 3)
print("Original Array:")
print(Z)

print("\nCentered 3x3 on (2,2):")
print(extract_centered_subpart(Z, center, shape))

print("\nCentered 5x5 on (0,0) (requires padding):")
center_pad = (0, 0)
shape_pad = (5, 5)
print(extract_centered_subpart(Z, center_pad, shape_pad, fill_value=-1))

Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Centered 3x3 on (2,2):
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Centered 5x5 on (0,0) (requires padding):
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1  0  1  2]
 [-1 -1  5  6  7]
 [-1 -1 10 11 12]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


3#### 82. Compute a matrix rank (★★★)

In [9]:
A = np.random.uniform(0, 1, (3, 3))
A[2] = A[0] + A[1]  # Make the matrix rank deficient (rank should be 2)
rank = np.linalg.matrix_rank(A)
print(f"Matrix:\n{A}")
print(f"Rank: {rank}")

Matrix:
[[0.01267451 0.07083742 0.32073261]
 [0.1574143  0.51825928 0.49236276]
 [0.1700888  0.58909671 0.81309537]]
Rank: 2


#### 83. How to find the most frequent value in an array?

In [10]:
Z = np.random.randint(0, 10, 50)
counts = np.bincount(Z)
most_frequent_value = np.argmax(counts)
print(f"Array: {Z}")
print(f"Most frequent value: {most_frequent_value}")

Array: [9 1 2 0 7 7 3 9 7 7 3 9 1 3 9 8 0 5 6 2 4 3 5 8 1 8 3 8 3 3 2 9 9 8 1 1 4
 6 1 7 6 9 8 3 1 7 1 8 0 9]
Most frequent value: 1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [11]:
Z = np.random.randint(0, 10, (10, 10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
R = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n),
                                    strides=Z.strides + Z.strides)
print(f"Original 10x10 array:\n{Z}")
print(f"\nNumber of 3x3 blocks: {R.shape[0]}x{R.shape[1]}")
print(f"\nExample of the first 3x3 block:\n{R[0, 0]}")

Original 10x10 array:
[[3 5 6 1 1 5 8 1 0 3]
 [5 2 6 8 3 3 5 7 5 9]
 [5 3 0 5 5 2 7 0 8 9]
 [7 5 8 8 2 3 2 7 5 3]
 [0 3 1 6 5 6 6 4 5 8]
 [3 6 2 0 2 4 0 9 0 8]
 [5 7 6 8 6 7 7 6 2 7]
 [8 9 6 6 5 9 5 7 0 8]
 [5 9 0 1 9 8 2 7 7 2]
 [2 1 8 0 7 7 6 0 9 8]]

Number of 3x3 blocks: 8x8

Example of the first 3x3 block:
[[3 5 6]
 [5 2 6]
 [5 3 0]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [12]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def as_symetric(Z):
    return Z.view(Symetric)

Z = np.zeros((5, 5))
S = as_symetric(Z)
S[1, 2] = 42
print(S)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0. 42.  0.  0.]
 [ 0. 42.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [13]:
p, n = 10, 5
M = np.ones((p, n, n))
V = np.ones((p, n, 1))

R = np.einsum('pij,pjk->ik', M, V)
print(R)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [14]:
Z = np.ones((16, 16))
n = 4
S = Z.reshape(Z.shape[0]//n, n, Z.shape[1]//n, n).sum(axis=(1, 3))
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [15]:
def iterate_gol(Z):
    # Count the number of active neighbors using a convolution-like sum
    # np.roll shifts the array to get neighbors
    N = (np.roll(np.roll(Z, 1, 0), 1, 1) +  # South-East
         np.roll(np.roll(Z, 1, 0), -1, 1) + # South-West
         np.roll(np.roll(Z, -1, 0), 1, 1) + # North-East
         np.roll(np.roll(Z, -1, 0), -1, 1) + # North-West
         np.roll(Z, 1, 0) +  # South
         np.roll(Z, -1, 0) + # North
         np.roll(Z, 0, 1) + # East
         np.roll(Z, 0, -1)) # West

    # 1. Any live cell with fewer than two live neighbors dies (underpopulation)
    # 2. Any live cell with two or three live neighbors lives (survival)
    # 3. Any live cell with more than three live neighbors dies (overpopulation)
    # 4. Any dead cell with exactly three live neighbors becomes a live cell (reproduction)

    # Update rules:
    # Rule 2: Live cell (Z=1) with 2 or 3 neighbors (N=2 or N=3) stays alive
    # Rule 4: Dead cell (Z=0) with 3 neighbors (N=3) comes to life
    Z = (N == 3) | (Z & (N == 2))
    return Z

# Example: create a simple glider pattern (period 4)
Z = np.zeros((10, 10), dtype=int)
Z[1, 2] = 1
Z[2, 3] = 1
Z[3, 1:4] = 1

print("Initial state:")
print(Z)

# Simulate one step
Z = iterate_gol(Z)
print("\nState after 1 iteration:")
print(Z)

Initial state:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

State after 1 iteration:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [18]:
Z =np.random.randint(0,100,10)
n = 3

large_n_value = np.partition(Z, -n)[-n:]
indices_largest_n = np.argpartition(Z, -n)[-n:]
print(f"Array: {Z}")
print(f"The {n} large value: {large_n_value}")
print(f"Indices of the {n} largest value: {indices_largest_n}")

Array: [65 44 41 73  6 48 80 25 18 13]
The 3 large value: [65 73 80]
Indices of the 3 largest value: [0 3 6]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [35]:
arrays = [np.array([1, 2]), np.array(['a', 'b', 'c']), np.array([10, 20])]
D = np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(D)

[['1' 'a' '10']
 ['1' 'b' '10']
 ['1' 'c' '10']
 ['2' 'a' '10']
 ['2' 'b' '10']
 ['2' 'c' '10']
 ['1' 'a' '20']
 ['1' 'b' '20']
 ['1' 'c' '20']
 ['2' 'a' '20']
 ['2' 'b' '20']
 ['2' 'c' '20']]


#### 91. How to create a record array from a regular array? (★★★)

In [34]:
Z = np.array([('Alice', 25, 165), ('Bob', 30, 180)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats='O, i4, i4')
print(R)

[('Alice', 25, 165) ('Bob', 30, 180)]


C:\Users\Dani_\AppData\Local\Temp\ipykernel_22876\321252693.py:2: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats='O, i4, i4')


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [33]:
Z = np.random.rand(1000)

R1 = Z**3

R2 = np.power(Z, 3)

R3 = Z * Z * Z

print(np.allclose(R1, R2))
print(np.allclose(R1, R3))

True
True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [38]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

A[0] = [B[0, 0], B[0, 1], B[1, 0]]
A[1] = [B[1, 0], B[1, 1], 9]

print("A:\n", A)
print("B:\n", B)

comparison = A[:, None, None, :] == B[None, :, :, None]

has_match = comparison.any(axis=3)
all_elements_match = has_match.all(axis=2)
final_mask = all_elements_match.all(axis=1)

result = A[final_mask]
print("\nRows of A containing all elements of EACH row of B (regardless of order):")
print(result)

A:
 [[0 0 2]
 [2 1 9]
 [2 3 2]
 [3 4 3]
 [4 1 2]
 [4 2 4]
 [0 2 2]
 [3 3 1]]
B:
 [[0 0]
 [2 1]]

Rows of A containing all elements of EACH row of B (regardless of order):
[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [28]:
Z = np.random.randint(0, 5, (10, 3))
Z[3, :] = 1  # Example equal row
Z[7, :] = 4
print("Original Array Z:")
print(Z)
equal_rows_mask = np.equal(np.max(Z, axis=1), np.min(Z, axis=1))
unequal_rows = Z[~equal_rows_mask]
print("\nRows with unequal values:")
print(unequal_rows)

Original Array Z:
[[0 2 1]
 [0 4 3]
 [2 1 1]
 [1 1 1]
 [4 0 4]
 [2 4 1]
 [2 2 3]
 [4 4 4]
 [4 1 1]
 [2 2 4]]

Rows with unequal values:
[[0 2 1]
 [0 4 3]
 [2 1 1]
 [4 0 4]
 [2 4 1]
 [2 2 3]
 [4 1 1]
 [2 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [26]:
I = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.uint8)
bits = 8
R = ((I[:, None] & (1 << np.arange(bits))) > 0).astype(int)
print(R[:, ::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0, 5, (10, 3))
Z[1] = Z[0]
Z[6] = Z[7]

print("Original Array Z:")
print(Z)

unique_rows = np.unique(Z, axis=0)

print("\nUnique Rows:")
print(unique_rows)

Original Array Z:
[[3 0 1]
 [3 0 1]
 [4 0 4]
 [0 2 2]
 [0 3 3]
 [0 1 3]
 [2 0 0]
 [2 0 0]
 [1 2 0]
 [3 4 0]]

Unique Rows:
[[0 1 3]
 [0 2 2]
 [0 3 3]
 [1 2 0]
 [2 0 0]
 [3 0 1]
 [3 4 0]
 [4 0 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [20]:
A = np.arange(3)
B = np.arange(3)

inner_einsum = np.einsum('i,i->', A, B)
inner_func = np.inner(A, B)
print(f"Inner Product: {inner_einsum} (np.inner: {inner_func})")

outer_einsum = np.einsum('i,j->ij', A, B)
outer_func = np.outer(A, B)
print(f"Outer Product:\n{outer_einsum}\n(np.outer:\n{outer_func})")

sum_einsum = np.einsum('i->', A)
sum_func = np.sum(A)
print(f"Sum: {sum_einsum} (np.sum: {sum_func})")

mul_einsum = np.einsum('i,i->i', A, B)
mul_func = A * B
print(f"Element-wise Multiplication: {mul_einsum} (A*B: {mul_func})")

Inner Product: 5 (np.inner: 5)
Outer Product:
[[0 0 0]
 [0 1 2]
 [0 2 4]]
(np.outer:
[[0 0 0]
 [0 1 2]
 [0 2 4]])
Sum: 3 (np.sum: 3)
Element-wise Multiplication: [0 1 4] (A*B: [0 1 4])


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [19]:
X = np.array([0.0, 1.0, 3.0, 6.0])
Y = np.array([0.0, 1.0, 1.0, 4.0])
n_samples = 10

dx = np.diff(Y)
dy = np.diff(X)
segment_lengths = np.sqrt(dx**2 + dy**2)

path_length = np.concatenate(([0.0], np.cumsum(segment_lengths)))
total_length = path_length[-1]

equidistant_points = np.linspace(0, total_length, n_samples)

X_samp = np.interp(equidistant_points, path_length, X)
Y_samp = np.interp(equidistant_points, path_length, Y)

print("X Sampled:", X_samp)
print("Y Sampled:", Y_samp)

X Sampled: [0.         0.60157928 1.2873096  2.13807119 2.98883277 3.59368286
 4.19526215 4.79684143 5.39842072 6.        ]
Y Sampled: [0.         0.60157928 1.         1.         1.         1.59368286
 2.19526215 2.79684143 3.39842072 4.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [12]:
n = 10
X = np.array([
    [1,2,7],
    [1,2,8],
    [-1,4,5],
    [2,4,4],
    [2.5,2.25,5.25]
])

is_intiger = (X % 1 == 0)
is_not_negative = (X>=0)
is_valid_type = np.all(is_intiger & is_not_negative, axis =1)

sums_to_n = (X.sum(axis = 1) == n)
multinomial_mask = is_valid_type & sums_to_n

valid_rows = X[multinomial_mask]
print(valid_rows)


[[1. 2. 7.]
 [2. 4. 4.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [7]:
import numpy as np

X =np.random.rand(1000)
N= 10000
M = len(X)

indices = np.random.randint(0, M, (N, M))
bootstrapped_samples = X[indices]

bootstrapped_means = bootstrapped_samples.mean(axis=1)

confidence_interval = np.percentile(bootstrapped_means, [2.5, 97.5])

print(f"Original Mean: {X.mean():.4f}")
print(f"Bootstrapped 95% Confidence Interval for the Mean : {confidence_interval}")

Original Mean: 0.5058
Bootstrapped 95% Confidence Interval for the Mean : [0.48773523 0.52411696]
